// Exercise library for the Gym tab, loaded only when the Gym tab opens (window.EXERCISES).
// Source: free-exercise-db by yuhonas, https://github.com/yuhonas/free-exercise-db (dist/exercises.json, commit f00c92c7dcf1216a928a52c3706c7ce8e2f71ed5),
// released under the Unlicense (public domain dedication, LICENSE.md in that repo). Trimmed to
// [name, primary muscles, equipment, category, image folder]; a picture is
// https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/<image folder>/0.jpg (same licence).
(function (g) { const EXERCISES = [
["3/4 Sit-Up","abdominals","body only","strength","3_4_Sit-Up"],
["90/90 Hamstring","hamstrings","body only","stretching","90_90_Hamstring"],
["Ab Crunch Machine","abdominals","machine","strength","Ab_Crunch_Machine"],
["Ab Roller","abdominals","other","strength","Ab_Roller"],
["Adductor","adductors","foam roll","stretching","Adductor"],
["Adductor/Groin","adductors","","stretching","Adductor_Groin"],
["Advanced Kettlebell Windmill","abdominals","kettlebells","strength","Advanced_Kettlebell_Windmill"],
["Air Bike","abdominals","body only","strength","Air_Bike"],
["All Fours Quad Stretch","quadriceps","body only","stretching","All_Fours_Quad_Stretch"],
["Alternate Hammer Curl","biceps","dumbbell","strength","Alternate_Hammer_Curl"],
["Alternate Heel Touchers","abdominals","body only","strength","Alternate_Heel_Touchers"],
["Alternate Incline Dumbbell Curl","biceps","dumbbell","strength","Alternate_Incline_Dumbbell_Curl"],
["Alternate Leg Diagonal Bound","quadriceps","","plyometrics","Alternate_Leg_Diagonal_Bound"],
["Alternating Cable Shoulder Press","shoulders","cable","strength","Alternating_Cable_Shoulder_Press"],
["Alternating Deltoid Raise","shoulders","dumbbell","strength","Alternating_Deltoid_Raise"],
["Alternating Floor Press","chest","kettlebells","strength","Alternating_Floor_Press"],
["Alternating Hang Clean","hamstrings","kettlebells","strength","Alternating_Hang_Clean"],
["Alternating Kettlebell Press","shoulders","kettlebells","strength","Alternating_Kettlebell_Press"],
["Alternating Kettlebell Row","middle back","kettlebells","strength","Alternating_Kettlebell_Row"],
["Alternating Renegade Row","middle back","kettlebells","strength","Alternating_Renegade_Row"],
["Ankle Circles","calves","","stretching","Ankle_Circles"],
["Ankle On The Knee","glutes","","stretching","Ankle_On_The_Knee"],
["Anterior Tibialis-SMR","calves","other","stretching","Anterior_Tibialis-SMR"],
["Anti-Gravity Press","shoulders","barbell","strength","Anti-Gravity_Press"],
["Arm Circles","shoulders","","stretching","Arm_Circles"],
["Arnold Dumbbell Press","shoulders","dumbbell","strength","Arnold_Dumbbell_Press"],
["Around The Worlds","chest","dumbbell","strength","Around_The_Worlds"],
["Atlas Stone Trainer","lower back","other","strongman","Atlas_Stone_Trainer"],
["Atlas Stones","lower back","other","strongman","Atlas_Stones"],
["Axle Deadlift","lower back","other","strongman","Axle_Deadlift"],
["Back Flyes - With Bands","shoulders","bands","strength","Back_Flyes_-_With_Bands"],
["Backward Drag","quadriceps","other","strongman","Backward_Drag"],
["Backward Medicine Ball Throw","shoulders","medicine ball","plyometrics","Backward_Medicine_Ball_Throw"],
["Balance Board","calves","other","strength","Balance_Board"],
["Ball Leg Curl","hamstrings","exercise ball","strength","Ball_Leg_Curl"],
["Band Assisted Pull-Up","lats","other","strength","Band_Assisted_Pull-Up"],
["Band Good Morning","hamstrings","bands","powerlifting","Band_Good_Morning"],
["Band Good Morning (Pull Through)","hamstrings","bands","powerlifting","Band_Good_Morning_Pull_Through"],
["Band Hip Adductions","adductors","bands","strength","Band_Hip_Adductions"],
["Band Pull Apart","shoulders","bands","strength","Band_Pull_Apart"],
["Band Skull Crusher","triceps","bands","strength","Band_Skull_Crusher"],
["Barbell Ab Rollout","abdominals","barbell","strength","Barbell_Ab_Rollout"],
["Barbell Ab Rollout - On Knees","abdominals","barbell","strength","Barbell_Ab_Rollout_-_On_Knees"],
["Barbell Bench Press - Medium Grip","chest","barbell","strength","Barbell_Bench_Press_-_Medium_Grip"],
["Barbell Curl","biceps","barbell","strength","Barbell_Curl"],
["Barbell Curls Lying Against An Incline","biceps","barbell","strength","Barbell_Curls_Lying_Against_An_Incline"],
["Barbell Deadlift","lower back","barbell","strength","Barbell_Deadlift"],
["Barbell Full Squat","quadriceps","barbell","strength","Barbell_Full_Squat"],
["Barbell Glute Bridge","glutes","barbell","powerlifting","Barbell_Glute_Bridge"],
["Barbell Guillotine Bench Press","chest","barbell","strength","Barbell_Guillotine_Bench_Press"],
["Barbell Hack Squat","quadriceps","barbell","strength","Barbell_Hack_Squat"],
["Barbell Hip Thrust","glutes","barbell","powerlifting","Barbell_Hip_Thrust"],
["Barbell Incline Bench Press - Medium Grip","chest","barbell","strength","Barbell_Incline_Bench_Press_-_Medium_Grip"],
["Barbell Incline Shoulder Raise","shoulders","barbell","strength","Barbell_Incline_Shoulder_Raise"],
["Barbell Lunge","quadriceps","barbell","strength","Barbell_Lunge"],
["Barbell Rear Delt Row","shoulders","barbell","strength","Barbell_Rear_Delt_Row"],
["Barbell Rollout from Bench","abdominals","barbell","strength","Barbell_Rollout_from_Bench"],
["Barbell Seated Calf Raise","calves","barbell","strength","Barbell_Seated_Calf_Raise"],
["Barbell Shoulder Press","shoulders","barbell","strength","Barbell_Shoulder_Press"],
["Barbell Shrug","traps","barbell","strength","Barbell_Shrug"],
["Barbell Shrug Behind The Back","traps","barbell","strength","Barbell_Shrug_Behind_The_Back"],
["Barbell Side Bend","abdominals","barbell","strength","Barbell_Side_Bend"],
["Barbell Side Split Squat","quadriceps","barbell","strength","Barbell_Side_Split_Squat"],
["Barbell Squat","quadriceps","barbell","strength","Barbell_Squat"],
["Barbell Squat To A Bench","quadriceps","barbell","strength","Barbell_Squat_To_A_Bench"],
["Barbell Step Ups","quadriceps","barbell","strength","Barbell_Step_Ups"],
["Barbell Walking Lunge","quadriceps","barbell","strength","Barbell_Walking_Lunge"],
["Battling Ropes","shoulders","other","strength","Battling_Ropes"],
["Bear Crawl Sled Drags","quadriceps","other","strongman","Bear_Crawl_Sled_Drags"],
["Behind Head Chest Stretch","chest","other","stretching","Behind_Head_Chest_Stretch"],
["Bench Dips","triceps","body only","strength","Bench_Dips"],
["Bench Jump","quadriceps","body only","plyometrics","Bench_Jump"],
["Bench Press - Powerlifting","triceps","barbell","powerlifting","Bench_Press_-_Powerlifting"],
["Bench Press - With Bands","chest","bands","strength","Bench_Press_-_With_Bands"],
["Bench Press with Chains","triceps","barbell","powerlifting","Bench_Press_with_Chains"],
["Bench Sprint","quadriceps","other","plyometrics","Bench_Sprint"],
["Bent-Arm Barbell Pullover","lats","barbell","strength","Bent-Arm_Barbell_Pullover"],
["Bent-Arm Dumbbell Pullover","chest","dumbbell","strength","Bent-Arm_Dumbbell_Pullover"],
["Bent-Knee Hip Raise","abdominals","body only","strength","Bent-Knee_Hip_Raise"],
["Bent Over Barbell Row","middle back","barbell","strength","Bent_Over_Barbell_Row"],
["Bent Over Dumbbell Rear Delt Raise With Head On Bench","shoulders","dumbbell","strength","Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench"],
["Bent Over Low-Pulley Side Lateral","shoulders","cable","strength","Bent_Over_Low-Pulley_Side_Lateral"],
["Bent Over One-Arm Long Bar Row","middle back","barbell","strength","Bent_Over_One-Arm_Long_Bar_Row"],
["Bent Over Two-Arm Long Bar Row","middle back","barbell","strength","Bent_Over_Two-Arm_Long_Bar_Row"],
["Bent Over Two-Dumbbell Row","middle back","dumbbell","strength","Bent_Over_Two-Dumbbell_Row"],
["Bent Over Two-Dumbbell Row With Palms In","middle back","dumbbell","strength","Bent_Over_Two-Dumbbell_Row_With_Palms_In"],
["Bent Press","abdominals","kettlebells","strength","Bent_Press"],
["Bicycling","quadriceps","other","cardio","Bicycling"],
["Bicycling, Stationary","quadriceps","machine","cardio","Bicycling_Stationary"],
["Board Press","triceps","barbell","powerlifting","Board_Press"],
["Body-Up","triceps","body only","strength","Body-Up"],
["Body Tricep Press","triceps","body only","strength","Body_Tricep_Press"],
["Bodyweight Flyes","chest","e-z curl bar","strength","Bodyweight_Flyes"],
["Bodyweight Mid Row","middle back","other","strength","Bodyweight_Mid_Row"],
["Bodyweight Squat","quadriceps","body only","strength","Bodyweight_Squat"],
["Bodyweight Walking Lunge","quadriceps","","strength","Bodyweight_Walking_Lunge"],
["Bosu Ball Cable Crunch With Side Bends","abdominals","cable","strength","Bosu_Ball_Cable_Crunch_With_Side_Bends"],
["Bottoms-Up Clean From The Hang Position","forearms","kettlebells","strength","Bottoms-Up_Clean_From_The_Hang_Position"],
["Bottoms Up","abdominals","body only","strength","Bottoms_Up"],
["Box Jump (Multiple Response)","hamstrings","other","plyometrics","Box_Jump_Multiple_Response"],
["Box Skip","hamstrings","other","plyometrics","Box_Skip"],
["Box Squat","quadriceps","barbell","powerlifting","Box_Squat"],
["Box Squat with Bands","quadriceps","barbell","powerlifting","Box_Squat_with_Bands"],
["Box Squat with Chains","quadriceps","barbell","strength","Box_Squat_with_Chains"],
["Brachialis-SMR","biceps","foam roll","stretching","Brachialis-SMR"],
["Bradford/Rocky Presses","shoulders","barbell","strength","Bradford_Rocky_Presses"],
["Butt-Ups","abdominals","body only","strength","Butt-Ups"],
["Butt Lift (Bridge)","glutes","body only","strength","Butt_Lift_Bridge"],
["Butterfly","chest","machine","strength","Butterfly"],
["Cable Chest Press","chest","cable","strength","Cable_Chest_Press"],
["Cable Crossover","chest","cable","strength","Cable_Crossover"],
["Cable Crunch","abdominals","cable","strength","Cable_Crunch"],
["Cable Deadlifts","quadriceps","cable","strength","Cable_Deadlifts"],
["Cable Hammer Curls - Rope Attachment","biceps","cable","strength","Cable_Hammer_Curls_-_Rope_Attachment"],
["Cable Hip Adduction","quadriceps","cable","strength","Cable_Hip_Adduction"],
["Cable Incline Pushdown","lats","cable","strength","Cable_Incline_Pushdown"],
["Cable Incline Triceps Extension","triceps","cable","strength","Cable_Incline_Triceps_Extension"],
["Cable Internal Rotation","shoulders","cable","strength","Cable_Internal_Rotation"],
["Cable Iron Cross","chest","cable","strength","Cable_Iron_Cross"],
["Cable Judo Flip","abdominals","cable","strength","Cable_Judo_Flip"],
["Cable Lying Triceps Extension","triceps","cable","strength","Cable_Lying_Triceps_Extension"],
["Cable One Arm Tricep Extension","triceps","cable","strength","Cable_One_Arm_Tricep_Extension"],
["Cable Preacher Curl","biceps","cable","strength","Cable_Preacher_Curl"],
["Cable Rear Delt Fly","shoulders","cable","strength","Cable_Rear_Delt_Fly"],
["Cable Reverse Crunch","abdominals","cable","strength","Cable_Reverse_Crunch"],
["Cable Rope Overhead Triceps Extension","triceps","cable","strength","Cable_Rope_Overhead_Triceps_Extension"],
["Cable Rope Rear-Delt Rows","shoulders","cable","strength","Cable_Rope_Rear-Delt_Rows"],
["Cable Russian Twists","abdominals","cable","strength","Cable_Russian_Twists"],
["Cable Seated Crunch","abdominals","cable","strength","Cable_Seated_Crunch"],
["Cable Seated Lateral Raise","shoulders","cable","strength","Cable_Seated_Lateral_Raise"],
["Cable Shoulder Press","shoulders","cable","strength","Cable_Shoulder_Press"],
["Cable Shrugs","traps","cable","strength","Cable_Shrugs"],
["Cable Wrist Curl","forearms","cable","strength","Cable_Wrist_Curl"],
["Calf-Machine Shoulder Shrug","traps","machine","strength","Calf-Machine_Shoulder_Shrug"],
["Calf Press","calves","machine","strength","Calf_Press"],
["Calf Press On The Leg Press Machine","calves","machine","strength","Calf_Press_On_The_Leg_Press_Machine"],
["Calf Raise On A Dumbbell","calves","dumbbell","strength","Calf_Raise_On_A_Dumbbell"],
["Calf Raises - With Bands","calves","bands","strength","Calf_Raises_-_With_Bands"],
["Calf Stretch Elbows Against Wall","calves","","stretching","Calf_Stretch_Elbows_Against_Wall"],
["Calf Stretch Hands Against Wall","calves","","stretching","Calf_Stretch_Hands_Against_Wall"],
["Calves-SMR","calves","foam roll","stretching","Calves-SMR"],
["Car Deadlift","quadriceps","other","strongman","Car_Deadlift"],
["Car Drivers","shoulders","barbell","strength","Car_Drivers"],
["Carioca Quick Step","adductors","","plyometrics","Carioca_Quick_Step"],
["Cat Stretch","lower back","","stretching","Cat_Stretch"],
["Catch and Overhead Throw","lats","medicine ball","plyometrics","Catch_and_Overhead_Throw"],
["Chain Handle Extension","triceps","other","powerlifting","Chain_Handle_Extension"],
["Chain Press","chest","other","powerlifting","Chain_Press"],
["Chair Leg Extended Stretch","hamstrings","other","stretching","Chair_Leg_Extended_Stretch"],
["Chair Lower Back Stretch","lats","","stretching","Chair_Lower_Back_Stretch"],
["Chair Squat","quadriceps","machine","strength","Chair_Squat"],
["Chair Upper Body Stretch","shoulders","other","stretching","Chair_Upper_Body_Stretch"],
["Chest And Front Of Shoulder Stretch","chest","other","stretching","Chest_And_Front_Of_Shoulder_Stretch"],
["Chest Push from 3 point stance","chest","medicine ball","plyometrics","Chest_Push_from_3_point_stance"],
["Chest Push (multiple response)","chest","medicine ball","plyometrics","Chest_Push_multiple_response"],
["Chest Push (single response)","chest","medicine ball","plyometrics","Chest_Push_single_response"],
["Chest Push with Run Release","chest","medicine ball","plyometrics","Chest_Push_with_Run_Release"],
["Chest Stretch on Stability Ball","chest","exercise ball","stretching","Chest_Stretch_on_Stability_Ball"],
["Child's Pose","lower back","","stretching","Childs_Pose"],
["Chin-Up","lats","body only","strength","Chin-Up"],
["Chin To Chest Stretch","neck","","stretching","Chin_To_Chest_Stretch"],
["Circus Bell","shoulders","other","strongman","Circus_Bell"],
["Clean","hamstrings","barbell","olympic weightlifting","Clean"],
["Clean Deadlift","hamstrings","barbell","olympic weightlifting","Clean_Deadlift"],
["Clean Pull","quadriceps","barbell","olympic weightlifting","Clean_Pull"],
["Clean Shrug","traps","barbell","olympic weightlifting","Clean_Shrug"],
["Clean and Jerk","shoulders","barbell","olympic weightlifting","Clean_and_Jerk"],
["Clean and Press","shoulders","barbell","strength","Clean_and_Press"],
["Clean from Blocks","quadriceps","barbell","olympic weightlifting","Clean_from_Blocks"],
["Clock Push-Up","chest","body only","strength","Clock_Push-Up"],
["Close-Grip Barbell Bench Press","triceps","barbell","strength","Close-Grip_Barbell_Bench_Press"],
["Close-Grip Dumbbell Press","triceps","dumbbell","strength","Close-Grip_Dumbbell_Press"],
["Close-Grip EZ-Bar Curl with Band","biceps","e-z curl bar","strength","Close-Grip_EZ-Bar_Curl_with_Band"],
["Close-Grip EZ-Bar Press","triceps","e-z curl bar","strength","Close-Grip_EZ-Bar_Press"],
["Close-Grip EZ Bar Curl","biceps","barbell","strength","Close-Grip_EZ_Bar_Curl"],
["Close-Grip Front Lat Pulldown","lats","cable","strength","Close-Grip_Front_Lat_Pulldown"],
["Close-Grip Push-Up off of a Dumbbell","triceps","body only","strength","Close-Grip_Push-Up_off_of_a_Dumbbell"],
["Close-Grip Standing Barbell Curl","biceps","barbell","strength","Close-Grip_Standing_Barbell_Curl"],
["Cocoons","abdominals","body only","strength","Cocoons"],
["Conan's Wheel","quadriceps","other","strongman","Conans_Wheel"],
["Concentration Curls","biceps","dumbbell","strength","Concentration_Curls"],
["Cross-Body Crunch","abdominals","body only","strength","Cross-Body_Crunch"],
["Cross Body Hammer Curl","biceps","dumbbell","strength","Cross_Body_Hammer_Curl"],
["Cross Over - With Bands","chest","bands","strength","Cross_Over_-_With_Bands"],
["Crossover Reverse Lunge","lower back","","stretching","Crossover_Reverse_Lunge"],
["Crucifix","shoulders","other","strongman","Crucifix"],
["Crunch - Hands Overhead","abdominals","body only","strength","Crunch_-_Hands_Overhead"],
["Crunch - Legs On Exercise Ball","abdominals","body only","strength","Crunch_-_Legs_On_Exercise_Ball"],
["Crunches","abdominals","body only","strength","Crunches"],
["Cuban Press","shoulders","dumbbell","strength","Cuban_Press"],
["Dancer's Stretch","lower back","","stretching","Dancers_Stretch"],
["Dead Bug","abdominals","body only","strength","Dead_Bug"],
["Deadlift with Bands","lower back","barbell","powerlifting","Deadlift_with_Bands"],
["Deadlift with Chains","lower back","barbell","powerlifting","Deadlift_with_Chains"],
["Decline Barbell Bench Press","chest","barbell","strength","Decline_Barbell_Bench_Press"],
["Decline Close-Grip Bench To Skull Crusher","triceps","barbell","strength","Decline_Close-Grip_Bench_To_Skull_Crusher"],
["Decline Crunch","abdominals","body only","strength","Decline_Crunch"],
["Decline Dumbbell Bench Press","chest","dumbbell","strength","Decline_Dumbbell_Bench_Press"],
["Decline Dumbbell Flyes","chest","dumbbell","strength","Decline_Dumbbell_Flyes"],
["Decline Dumbbell Triceps Extension","triceps","dumbbell","strength","Decline_Dumbbell_Triceps_Extension"],
["Decline EZ Bar Triceps Extension","triceps","barbell","strength","Decline_EZ_Bar_Triceps_Extension"],
["Decline Oblique Crunch","abdominals","body only","strength","Decline_Oblique_Crunch"],
["Decline Push-Up","chest","","strength","Decline_Push-Up"],
["Decline Reverse Crunch","abdominals","body only","strength","Decline_Reverse_Crunch"],
["Decline Smith Press","chest","machine","strength","Decline_Smith_Press"],
["Deficit Deadlift","lower back","barbell","powerlifting","Deficit_Deadlift"],
["Depth Jump Leap","quadriceps","other","plyometrics","Depth_Jump_Leap"],
["Dip Machine","triceps","machine","strength","Dip_Machine"],
["Dips - Chest Version","chest","other","strength","Dips_-_Chest_Version"],
["Dips - Triceps Version","triceps","body only","strength","Dips_-_Triceps_Version"],
["Donkey Calf Raises","calves","other","strength","Donkey_Calf_Raises"],
["Double Kettlebell Alternating Hang Clean","hamstrings","kettlebells","strength","Double_Kettlebell_Alternating_Hang_Clean"],
["Double Kettlebell Jerk","shoulders","kettlebells","strength","Double_Kettlebell_Jerk"],
["Double Kettlebell Push Press","shoulders","kettlebells","strength","Double_Kettlebell_Push_Press"],
["Double Kettlebell Snatch","shoulders","kettlebells","strength","Double_Kettlebell_Snatch"],
["Double Kettlebell Windmill","abdominals","kettlebells","strength","Double_Kettlebell_Windmill"],
["Double Leg Butt Kick","quadriceps","body only","plyometrics","Double_Leg_Butt_Kick"],
["Downward Facing Balance","glutes","exercise ball","strength","Downward_Facing_Balance"],
["Drag Curl","biceps","barbell","strength","Drag_Curl"],
["Drop Push","chest","other","plyometrics","Drop_Push"],
["Dumbbell Alternate Bicep Curl","biceps","dumbbell","strength","Dumbbell_Alternate_Bicep_Curl"],
["Dumbbell Bench Press","chest","dumbbell","strength","Dumbbell_Bench_Press"],
["Dumbbell Bench Press with Neutral Grip","chest","dumbbell","strength","Dumbbell_Bench_Press_with_Neutral_Grip"],
["Dumbbell Bicep Curl","biceps","dumbbell","strength","Dumbbell_Bicep_Curl"],
["Dumbbell Clean","hamstrings","dumbbell","strength","Dumbbell_Clean"],
["Dumbbell Floor Press","triceps","dumbbell","powerlifting","Dumbbell_Floor_Press"],
["Dumbbell Flyes","chest","dumbbell","strength","Dumbbell_Flyes"],
["Dumbbell Incline Row","middle back","dumbbell","strength","Dumbbell_Incline_Row"],
["Dumbbell Incline Shoulder Raise","shoulders","dumbbell","strength","Dumbbell_Incline_Shoulder_Raise"],
["Dumbbell Lunges","quadriceps","dumbbell","strength","Dumbbell_Lunges"],
["Dumbbell Lying One-Arm Rear Lateral Raise","shoulders","dumbbell","strength","Dumbbell_Lying_One-Arm_Rear_Lateral_Raise"],
["Dumbbell Lying Pronation","forearms","dumbbell","strength","Dumbbell_Lying_Pronation"],
["Dumbbell Lying Rear Lateral Raise","shoulders","dumbbell","strength","Dumbbell_Lying_Rear_Lateral_Raise"],
["Dumbbell Lying Supination","forearms","dumbbell","strength","Dumbbell_Lying_Supination"],
["Dumbbell One-Arm Shoulder Press","shoulders","dumbbell","strength","Dumbbell_One-Arm_Shoulder_Press"],
["Dumbbell One-Arm Triceps Extension","triceps","dumbbell","strength","Dumbbell_One-Arm_Triceps_Extension"],
["Dumbbell One-Arm Upright Row","shoulders","dumbbell","strength","Dumbbell_One-Arm_Upright_Row"],
["Dumbbell Prone Incline Curl","biceps","dumbbell","strength","Dumbbell_Prone_Incline_Curl"],
["Dumbbell Raise","shoulders","dumbbell","strength","Dumbbell_Raise"],
["Dumbbell Rear Lunge","quadriceps","dumbbell","strength","Dumbbell_Rear_Lunge"],
["Dumbbell Scaption","shoulders","dumbbell","strength","Dumbbell_Scaption"],
["Dumbbell Seated Box Jump","quadriceps","dumbbell","plyometrics","Dumbbell_Seated_Box_Jump"],
["Dumbbell Seated One-Leg Calf Raise","calves","dumbbell","strength","Dumbbell_Seated_One-Leg_Calf_Raise"],
["Dumbbell Shoulder Press","shoulders","dumbbell","strength","Dumbbell_Shoulder_Press"],
["Dumbbell Shrug","traps","dumbbell","strength","Dumbbell_Shrug"],
["Dumbbell Side Bend","abdominals","dumbbell","strength","Dumbbell_Side_Bend"],
["Dumbbell Squat","quadriceps","dumbbell","strength","Dumbbell_Squat"],
["Dumbbell Squat To A Bench","quadriceps","dumbbell","strength","Dumbbell_Squat_To_A_Bench"],
["Dumbbell Step Ups","quadriceps","dumbbell","strength","Dumbbell_Step_Ups"],
["Dumbbell Tricep Extension -Pronated Grip","triceps","dumbbell","strength","Dumbbell_Tricep_Extension_-Pronated_Grip"],
["Dynamic Back Stretch","lats","","stretching","Dynamic_Back_Stretch"],
["Dynamic Chest Stretch","chest","","stretching","Dynamic_Chest_Stretch"],
["EZ-Bar Curl","biceps","e-z curl bar","strength","EZ-Bar_Curl"],
["EZ-Bar Skullcrusher","triceps","e-z curl bar","strength","EZ-Bar_Skullcrusher"],
["Elbow Circles","shoulders","","stretching","Elbow_Circles"],
["Elbow to Knee","abdominals","body only","strength","Elbow_to_Knee"],
["Elbows Back","chest","","stretching","Elbows_Back"],
["Elevated Back Lunge","quadriceps","barbell","strength","Elevated_Back_Lunge"],
["Elevated Cable Rows","lats","cable","strength","Elevated_Cable_Rows"],
["Elliptical Trainer","quadriceps","machine","cardio","Elliptical_Trainer"],
["Exercise Ball Crunch","abdominals","exercise ball","strength","Exercise_Ball_Crunch"],
["Exercise Ball Pull-In","abdominals","exercise ball","strength","Exercise_Ball_Pull-In"],
["Extended Range One-Arm Kettlebell Floor Press","chest","kettlebells","strength","Extended_Range_One-Arm_Kettlebell_Floor_Press"],
["External Rotation","shoulders","dumbbell","strength","External_Rotation"],
["External Rotation with Band","shoulders","bands","strength","External_Rotation_with_Band"],
["External Rotation with Cable","shoulders","cable","strength","External_Rotation_with_Cable"],
["Face Pull","shoulders","cable","strength","Face_Pull"],
["Farmer's Walk","forearms","other","strongman","Farmers_Walk"],
["Fast Skipping","quadriceps","body only","plyometrics","Fast_Skipping"],
["Finger Curls","forearms","barbell","strength","Finger_Curls"],
["Flat Bench Cable Flyes","chest","cable","strength","Flat_Bench_Cable_Flyes"],
["Flat Bench Leg Pull-In","abdominals","body only","strength","Flat_Bench_Leg_Pull-In"],
["Flat Bench Lying Leg Raise","abdominals","body only","strength","Flat_Bench_Lying_Leg_Raise"],
["Flexor Incline Dumbbell Curls","biceps","dumbbell","strength","Flexor_Incline_Dumbbell_Curls"],
["Floor Glute-Ham Raise","hamstrings","","strength","Floor_Glute-Ham_Raise"],
["Floor Press","triceps","barbell","powerlifting","Floor_Press"],
["Floor Press with Chains","triceps","barbell","powerlifting","Floor_Press_with_Chains"],
["Flutter Kicks","glutes","body only","strength","Flutter_Kicks"],
["Foot-SMR","calves","other","stretching","Foot-SMR"],
["Forward Drag with Press","chest","other","strongman","Forward_Drag_with_Press"],
["Frankenstein Squat","quadriceps","barbell","olympic weightlifting","Frankenstein_Squat"],
["Freehand Jump Squat","quadriceps","body only","strength","Freehand_Jump_Squat"],
["Frog Hops","quadriceps","","stretching","Frog_Hops"],
["Frog Sit-Ups","abdominals","body only","strength","Frog_Sit-Ups"],
["Front Barbell Squat","quadriceps","barbell","strength","Front_Barbell_Squat"],
["Front Barbell Squat To A Bench","quadriceps","barbell","strength","Front_Barbell_Squat_To_A_Bench"],
["Front Box Jump","hamstrings","other","plyometrics","Front_Box_Jump"],
["Front Cable Raise","shoulders","cable","strength","Front_Cable_Raise"],
["Front Cone Hops (or hurdle hops)","quadriceps","other","plyometrics","Front_Cone_Hops_or_hurdle_hops"],
["Front Dumbbell Raise","shoulders","dumbbell","strength","Front_Dumbbell_Raise"],
["Front Incline Dumbbell Raise","shoulders","dumbbell","strength","Front_Incline_Dumbbell_Raise"],
["Front Leg Raises","hamstrings","body only","stretching","Front_Leg_Raises"],
["Front Plate Raise","shoulders","other","strength","Front_Plate_Raise"],
["Front Raise And Pullover","chest","barbell","strength","Front_Raise_And_Pullover"],
["Front Squat (Clean Grip)","quadriceps","barbell","strength","Front_Squat_Clean_Grip"],
["Front Squats With Two Kettlebells","quadriceps","kettlebells","strength","Front_Squats_With_Two_Kettlebells"],
["Front Two-Dumbbell Raise","shoulders","dumbbell","strength","Front_Two-Dumbbell_Raise"],
["Full Range-Of-Motion Lat Pulldown","lats","cable","strength","Full_Range-Of-Motion_Lat_Pulldown"],
["Gironda Sternum Chins","lats","other","strength","Gironda_Sternum_Chins"],
["Glute Ham Raise","hamstrings","machine","powerlifting","Glute_Ham_Raise"],
["Glute Kickback","glutes","body only","strength","Glute_Kickback"],
["Goblet Squat","quadriceps","kettlebells","strength","Goblet_Squat"],
["Good Morning","hamstrings","barbell","powerlifting","Good_Morning"],
["Good Morning off Pins","hamstrings","barbell","powerlifting","Good_Morning_off_Pins"],
["Gorilla Chin/Crunch","abdominals","body only","strength","Gorilla_Chin_Crunch"],
["Groin and Back Stretch","adductors","","stretching","Groin_and_Back_Stretch"],
["Groiners","adductors","body only","stretching","Groiners"],
["Hack Squat","quadriceps","machine","strength","Hack_Squat"],
["Hammer Curls","biceps","dumbbell","strength","Hammer_Curls"],
["Hammer Grip Incline DB Bench Press","chest","dumbbell","strength","Hammer_Grip_Incline_DB_Bench_Press"],
["Hamstring-SMR","hamstrings","foam roll","stretching","Hamstring-SMR"],
["Hamstring Stretch","hamstrings","","stretching","Hamstring_Stretch"],
["Handstand Push-Ups","shoulders","body only","strength","Handstand_Push-Ups"],
["Hang Clean","quadriceps","barbell","olympic weightlifting","Hang_Clean"],
["Hang Clean - Below the Knees","quadriceps","barbell","olympic weightlifting","Hang_Clean_-_Below_the_Knees"],
["Hang Snatch","hamstrings","barbell","olympic weightlifting","Hang_Snatch"],
["Hang Snatch - Below Knees","hamstrings","barbell","olympic weightlifting","Hang_Snatch_-_Below_Knees"],
["Hanging Bar Good Morning","hamstrings","barbell","powerlifting","Hanging_Bar_Good_Morning"],
["Hanging Leg Raise","abdominals","body only","strength","Hanging_Leg_Raise"],
["Hanging Pike","abdominals","body only","strength","Hanging_Pike"],
["Heaving Snatch Balance","quadriceps","barbell","olympic weightlifting","Heaving_Snatch_Balance"],
["Heavy Bag Thrust","chest","other","plyometrics","Heavy_Bag_Thrust"],
["High Cable Curls","biceps","cable","strength","High_Cable_Curls"],
["Hip Circles (prone)","abductors","body only","stretching","Hip_Circles_prone"],
["Hip Extension with Bands","glutes","bands","strength","Hip_Extension_with_Bands"],
["Hip Flexion with Band","quadriceps","bands","strength","Hip_Flexion_with_Band"],
["Hip Lift with Band","glutes","bands","powerlifting","Hip_Lift_with_Band"],
["Hug A Ball","lower back","exercise ball","stretching","Hug_A_Ball"],
["Hug Knees To Chest","lower back","","stretching","Hug_Knees_To_Chest"],
["Hurdle Hops","hamstrings","other","plyometrics","Hurdle_Hops"],
["Hyperextensions (Back Extensions)","lower back","other","strength","Hyperextensions_Back_Extensions"],
["Hyperextensions With No Hyperextension Bench","lower back","body only","strength","Hyperextensions_With_No_Hyperextension_Bench"],
["IT Band and Glute Stretch","abductors","other","stretching","IT_Band_and_Glute_Stretch"],
["Iliotibial Tract-SMR","abductors","foam roll","stretching","Iliotibial_Tract-SMR"],
["Inchworm","hamstrings","body only","stretching","Inchworm"],
["Incline Barbell Triceps Extension","triceps","barbell","strength","Incline_Barbell_Triceps_Extension"],
["Incline Bench Pull","middle back","barbell","strength","Incline_Bench_Pull"],
["Incline Cable Chest Press","chest","cable","strength","Incline_Cable_Chest_Press"],
["Incline Cable Flye","chest","cable","strength","Incline_Cable_Flye"],
["Incline Dumbbell Bench With Palms Facing In","chest","dumbbell","strength","Incline_Dumbbell_Bench_With_Palms_Facing_In"],
["Incline Dumbbell Curl","biceps","dumbbell","strength","Incline_Dumbbell_Curl"],
["Incline Dumbbell Flyes","chest","dumbbell","strength","Incline_Dumbbell_Flyes"],
["Incline Dumbbell Flyes - With A Twist","chest","dumbbell","strength","Incline_Dumbbell_Flyes_-_With_A_Twist"],
["Incline Dumbbell Press","chest","dumbbell","strength","Incline_Dumbbell_Press"],
["Incline Hammer Curls","biceps","dumbbell","strength","Incline_Hammer_Curls"],
["Incline Inner Biceps Curl","biceps","dumbbell","strength","Incline_Inner_Biceps_Curl"],
["Incline Push-Up","chest","body only","strength","Incline_Push-Up"],
["Incline Push-Up Close-Grip","triceps","body only","strength","Incline_Push-Up_Close-Grip"],
["Incline Push-Up Depth Jump","chest","other","plyometrics","Incline_Push-Up_Depth_Jump"],
["Incline Push-Up Medium","chest","body only","strength","Incline_Push-Up_Medium"],
["Incline Push-Up Reverse Grip","chest","body only","strength","Incline_Push-Up_Reverse_Grip"],
["Incline Push-Up Wide","chest","body only","strength","Incline_Push-Up_Wide"],
["Intermediate Groin Stretch","hamstrings","other","stretching","Intermediate_Groin_Stretch"],
["Intermediate Hip Flexor and Quad Stretch","quadriceps","other","stretching","Intermediate_Hip_Flexor_and_Quad_Stretch"],
["Internal Rotation with Band","shoulders","bands","strength","Internal_Rotation_with_Band"],
["Inverted Row","middle back","","strength","Inverted_Row"],
["Inverted Row with Straps","middle back","other","strength","Inverted_Row_with_Straps"],
["Iron Cross","shoulders","dumbbell","strength","Iron_Cross"],
["Iron Crosses (stretch)","quadriceps","","stretching","Iron_Crosses_stretch"],
["Isometric Chest Squeezes","chest","body only","plyometrics","Isometric_Chest_Squeezes"],
["Isometric Neck Exercise - Front And Back","neck","body only","strength","Isometric_Neck_Exercise_-_Front_And_Back"],
["Isometric Neck Exercise - Sides","neck","body only","strength","Isometric_Neck_Exercise_-_Sides"],
["Isometric Wipers","chest","body only","strength","Isometric_Wipers"],
["JM Press","triceps","barbell","strength","JM_Press"],
["Jackknife Sit-Up","abdominals","body only","strength","Jackknife_Sit-Up"],
["Janda Sit-Up","abdominals","body only","strength","Janda_Sit-Up"],
["Jefferson Squats","quadriceps","barbell","strength","Jefferson_Squats"],
["Jerk Balance","shoulders","barbell","olympic weightlifting","Jerk_Balance"],
["Jerk Dip Squat","quadriceps","barbell","olympic weightlifting","Jerk_Dip_Squat"],
["Jogging, Treadmill","quadriceps","machine","cardio","Jogging_Treadmill"],
["Keg Load","lower back","other","strongman","Keg_Load"],
["Kettlebell Arnold Press","shoulders","kettlebells","strength","Kettlebell_Arnold_Press"],
["Kettlebell Dead Clean","hamstrings","kettlebells","strength","Kettlebell_Dead_Clean"],
["Kettlebell Figure 8","abdominals","kettlebells","strength","Kettlebell_Figure_8"],
["Kettlebell Halo","shoulders","kettlebells","strength",""],
["Kettlebell Halo with Overhead Extension","shoulders, triceps","kettlebells","strength",""],
["Kettlebell Hang Clean","hamstrings","kettlebells","strength","Kettlebell_Hang_Clean"],
["Kettlebell One-Legged Deadlift","hamstrings","kettlebells","strength","Kettlebell_One-Legged_Deadlift"],
["Kettlebell Overhead Triceps Extension","triceps","kettlebells","strength",""],
["Kettlebell Pass Between The Legs","abdominals","kettlebells","strength","Kettlebell_Pass_Between_The_Legs"],
["Kettlebell Pirate Ships","shoulders","kettlebells","strength","Kettlebell_Pirate_Ships"],
["Kettlebell Pistol Squat","quadriceps","kettlebells","strength","Kettlebell_Pistol_Squat"],
["Kettlebell Seated Press","shoulders","kettlebells","strength","Kettlebell_Seated_Press"],
["Kettlebell Seesaw Press","shoulders","kettlebells","strength","Kettlebell_Seesaw_Press"],
["Kettlebell Sumo High Pull","traps","kettlebells","strength","Kettlebell_Sumo_High_Pull"],
["Kettlebell Thruster","shoulders","kettlebells","strength","Kettlebell_Thruster"],
["Kettlebell Turkish Get-Up (Lunge style)","shoulders","kettlebells","strength","Kettlebell_Turkish_Get-Up_Lunge_style"],
["Kettlebell Turkish Get-Up (Squat style)","shoulders","kettlebells","strength","Kettlebell_Turkish_Get-Up_Squat_style"],
["Kettlebell Windmill","abdominals","kettlebells","strength","Kettlebell_Windmill"],
["Kipping Muscle Up","lats","other","strength","Kipping_Muscle_Up"],
["Knee Across The Body","glutes","","stretching","Knee_Across_The_Body"],
["Knee Circles","calves","body only","stretching","Knee_Circles"],
["Knee/Hip Raise On Parallel Bars","abdominals","other","strength","Knee_Hip_Raise_On_Parallel_Bars"],
["Knee Tuck Jump","hamstrings","body only","plyometrics","Knee_Tuck_Jump"],
["Kneeling Arm Drill","shoulders","","plyometrics","Kneeling_Arm_Drill"],
["Kneeling Cable Crunch With Alternating Oblique Twists","abdominals","cable","strength","Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists"],
["Kneeling Cable Triceps Extension","triceps","cable","strength","Kneeling_Cable_Triceps_Extension"],
["Kneeling Forearm Stretch","forearms","","stretching","Kneeling_Forearm_Stretch"],
["Kneeling High Pulley Row","lats","cable","strength","Kneeling_High_Pulley_Row"],
["Kneeling Hip Flexor","quadriceps","","stretching","Kneeling_Hip_Flexor"],
["Kneeling Jump Squat","glutes","barbell","olympic weightlifting","Kneeling_Jump_Squat"],
["Kneeling Single-Arm High Pulley Row","lats","cable","strength","Kneeling_Single-Arm_High_Pulley_Row"],
["Kneeling Squat","glutes","barbell","powerlifting","Kneeling_Squat"],
["Landmine 180's","abdominals","barbell","strength","Landmine_180s"],
["Landmine Linear Jammer","shoulders","barbell","strength","Landmine_Linear_Jammer"],
["Lateral Bound","adductors","body only","plyometrics","Lateral_Bound"],
["Lateral Box Jump","adductors","other","plyometrics","Lateral_Box_Jump"],
["Lateral Cone Hops","adductors","other","plyometrics","Lateral_Cone_Hops"],
["Lateral Raise - With Bands","shoulders","bands","strength","Lateral_Raise_-_With_Bands"],
["Latissimus Dorsi-SMR","lats","foam roll","stretching","Latissimus_Dorsi-SMR"],
["Leg-Over Floor Press","chest","kettlebells","strength","Leg-Over_Floor_Press"],
["Leg-Up Hamstring Stretch","hamstrings","","stretching","Leg-Up_Hamstring_Stretch"],
["Leg Extensions","quadriceps","machine","strength","Leg_Extensions"],
["Leg Lift","glutes","body only","strength","Leg_Lift"],
["Leg Press","quadriceps","machine","strength","Leg_Press"],
["Leg Pull-In","abdominals","body only","strength","Leg_Pull-In"],
["Leverage Chest Press","chest","machine","strength","Leverage_Chest_Press"],
["Leverage Deadlift","quadriceps","machine","strength","Leverage_Deadlift"],
["Leverage Decline Chest Press","chest","machine","strength","Leverage_Decline_Chest_Press"],
["Leverage High Row","middle back","machine","strength","Leverage_High_Row"],
["Leverage Incline Chest Press","chest","machine","strength","Leverage_Incline_Chest_Press"],
["Leverage Iso Row","lats","machine","strength","Leverage_Iso_Row"],
["Leverage Shoulder Press","shoulders","machine","strength","Leverage_Shoulder_Press"],
["Leverage Shrug","traps","machine","strength","Leverage_Shrug"],
["Linear 3-Part Start Technique","hamstrings","","plyometrics","Linear_3-Part_Start_Technique"],
["Linear Acceleration Wall Drill","hamstrings","","plyometrics","Linear_Acceleration_Wall_Drill"],
["Linear Depth Jump","quadriceps","other","plyometrics","Linear_Depth_Jump"],
["Log Lift","shoulders","other","strongman","Log_Lift"],
["London Bridges","lats","other","strength","London_Bridges"],
["Looking At Ceiling","quadriceps","","stretching","Looking_At_Ceiling"],
["Low Cable Crossover","chest","cable","strength","Low_Cable_Crossover"],
["Low Cable Triceps Extension","triceps","cable","strength","Low_Cable_Triceps_Extension"],
["Low Pulley Row To Neck","shoulders","cable","strength","Low_Pulley_Row_To_Neck"],
["Lower Back-SMR","lower back","foam roll","stretching","Lower_Back-SMR"],
["Lower Back Curl","abdominals","body only","stretching","Lower_Back_Curl"],
["Lunge Pass Through","hamstrings","kettlebells","strength","Lunge_Pass_Through"],
["Lunge Sprint","quadriceps","machine","strength","Lunge_Sprint"],
["Lying Bent Leg Groin","adductors","other","stretching","Lying_Bent_Leg_Groin"],
["Lying Cable Curl","biceps","cable","strength","Lying_Cable_Curl"],
["Lying Cambered Barbell Row","middle back","barbell","strength","Lying_Cambered_Barbell_Row"],
["Lying Close-Grip Bar Curl On High Pulley","biceps","cable","strength","Lying_Close-Grip_Bar_Curl_On_High_Pulley"],
["Lying Close-Grip Barbell Triceps Extension Behind The Head","triceps","barbell","strength","Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head"],
["Lying Close-Grip Barbell Triceps Press To Chin","triceps","e-z curl bar","strength","Lying_Close-Grip_Barbell_Triceps_Press_To_Chin"],
["Lying Crossover","abductors","body only","stretching","Lying_Crossover"],
["Lying Dumbbell Tricep Extension","triceps","dumbbell","strength","Lying_Dumbbell_Tricep_Extension"],
["Lying Face Down Plate Neck Resistance","neck","other","strength","Lying_Face_Down_Plate_Neck_Resistance"],
["Lying Face Up Plate Neck Resistance","neck","other","strength","Lying_Face_Up_Plate_Neck_Resistance"],
["Lying Glute","glutes","body only","stretching","Lying_Glute"],
["Lying Hamstring","hamstrings","other","stretching","Lying_Hamstring"],
["Lying High Bench Barbell Curl","biceps","barbell","strength","Lying_High_Bench_Barbell_Curl"],
["Lying Leg Curls","hamstrings","machine","strength","Lying_Leg_Curls"],
["Lying Machine Squat","quadriceps","machine","strength","Lying_Machine_Squat"],
["Lying One-Arm Lateral Raise","shoulders","dumbbell","strength","Lying_One-Arm_Lateral_Raise"],
["Lying Prone Quadriceps","quadriceps","body only","stretching","Lying_Prone_Quadriceps"],
["Lying Rear Delt Raise","shoulders","dumbbell","strength","Lying_Rear_Delt_Raise"],
["Lying Supine Dumbbell Curl","biceps","dumbbell","strength","Lying_Supine_Dumbbell_Curl"],
["Lying T-Bar Row","middle back","machine","strength","Lying_T-Bar_Row"],
["Lying Triceps Press","triceps","e-z curl bar","strength","Lying_Triceps_Press"],
["Machine Bench Press","chest","machine","strength","Machine_Bench_Press"],
["Machine Bicep Curl","biceps","machine","strength","Machine_Bicep_Curl"],
["Machine Preacher Curls","biceps","machine","strength","Machine_Preacher_Curls"],
["Machine Shoulder (Military) Press","shoulders","machine","strength","Machine_Shoulder_Military_Press"],
["Machine Triceps Extension","triceps","machine","strength","Machine_Triceps_Extension"],
["Medicine Ball Chest Pass","chest","medicine ball","plyometrics","Medicine_Ball_Chest_Pass"],
["Medicine Ball Full Twist","abdominals","medicine ball","plyometrics","Medicine_Ball_Full_Twist"],
["Medicine Ball Scoop Throw","shoulders","medicine ball","plyometrics","Medicine_Ball_Scoop_Throw"],
["Middle Back Shrug","middle back","dumbbell","strength","Middle_Back_Shrug"],
["Middle Back Stretch","middle back","","stretching","Middle_Back_Stretch"],
["Mixed Grip Chin","middle back","other","strength","Mixed_Grip_Chin"],
["Monster Walk","abductors","bands","strength","Monster_Walk"],
["Mountain Climbers","quadriceps","","plyometrics","Mountain_Climbers"],
["Moving Claw Series","hamstrings","","plyometrics","Moving_Claw_Series"],
["Muscle Snatch","hamstrings","barbell","olympic weightlifting","Muscle_Snatch"],
["Muscle Up","lats","other","strength","Muscle_Up"],
["Narrow Stance Hack Squats","quadriceps","machine","strength","Narrow_Stance_Hack_Squats"],
["Narrow Stance Leg Press","quadriceps","machine","strength","Narrow_Stance_Leg_Press"],
["Narrow Stance Squats","quadriceps","barbell","strength","Narrow_Stance_Squats"],
["Natural Glute Ham Raise","hamstrings","body only","strength","Natural_Glute_Ham_Raise"],
["Neck-SMR","neck","other","stretching","Neck-SMR"],
["Neck Press","chest","barbell","strength","Neck_Press"],
["Oblique Crunches","abdominals","body only","strength","Oblique_Crunches"],
["Oblique Crunches - On The Floor","abdominals","body only","strength","Oblique_Crunches_-_On_The_Floor"],
["Olympic Squat","quadriceps","barbell","olympic weightlifting","Olympic_Squat"],
["On-Your-Back Quad Stretch","quadriceps","other","stretching","On-Your-Back_Quad_Stretch"],
["On Your Side Quad Stretch","quadriceps","","stretching","On_Your_Side_Quad_Stretch"],
["One-Arm Dumbbell Row","middle back","dumbbell","strength","One-Arm_Dumbbell_Row"],
["One-Arm Flat Bench Dumbbell Flye","chest","dumbbell","strength","One-Arm_Flat_Bench_Dumbbell_Flye"],
["One-Arm High-Pulley Cable Side Bends","abdominals","cable","strength","One-Arm_High-Pulley_Cable_Side_Bends"],
["One-Arm Incline Lateral Raise","shoulders","dumbbell","strength","One-Arm_Incline_Lateral_Raise"],
["One-Arm Kettlebell Clean","hamstrings","kettlebells","strength","One-Arm_Kettlebell_Clean"],
["One-Arm Kettlebell Clean and Jerk","shoulders","kettlebells","strength","One-Arm_Kettlebell_Clean_and_Jerk"],
["One-Arm Kettlebell Floor Press","chest","kettlebells","strength","One-Arm_Kettlebell_Floor_Press"],
["One-Arm Kettlebell Jerk","shoulders","kettlebells","strength","One-Arm_Kettlebell_Jerk"],
["One-Arm Kettlebell Military Press To The Side","shoulders","kettlebells","strength","One-Arm_Kettlebell_Military_Press_To_The_Side"],
["One-Arm Kettlebell Para Press","shoulders","kettlebells","strength","One-Arm_Kettlebell_Para_Press"],
["One-Arm Kettlebell Push Press","shoulders","kettlebells","strength","One-Arm_Kettlebell_Push_Press"],
["One-Arm Kettlebell Row","middle back","kettlebells","strength","One-Arm_Kettlebell_Row"],
["One-Arm Kettlebell Snatch","shoulders","kettlebells","strength","One-Arm_Kettlebell_Snatch"],
["One-Arm Kettlebell Split Jerk","shoulders","kettlebells","strength","One-Arm_Kettlebell_Split_Jerk"],
["One-Arm Kettlebell Split Snatch","shoulders","kettlebells","strength","One-Arm_Kettlebell_Split_Snatch"],
["One-Arm Kettlebell Swings","hamstrings","kettlebells","strength","One-Arm_Kettlebell_Swings"],
["One-Arm Long Bar Row","middle back","barbell","strength","One-Arm_Long_Bar_Row"],
["One-Arm Medicine Ball Slam","abdominals","medicine ball","strength","One-Arm_Medicine_Ball_Slam"],
["One-Arm Open Palm Kettlebell Clean","hamstrings","kettlebells","strength","One-Arm_Open_Palm_Kettlebell_Clean"],
["One-Arm Overhead Kettlebell Squats","quadriceps","kettlebells","strength","One-Arm_Overhead_Kettlebell_Squats"],
["One-Arm Side Deadlift","quadriceps","barbell","strength","One-Arm_Side_Deadlift"],
["One-Arm Side Laterals","shoulders","dumbbell","strength","One-Arm_Side_Laterals"],
["One-Legged Cable Kickback","glutes","cable","strength","One-Legged_Cable_Kickback"],
["One Arm Against Wall","lats","","stretching","One_Arm_Against_Wall"],
["One Arm Chin-Up","middle back","other","strength","One_Arm_Chin-Up"],
["One Arm Dumbbell Bench Press","chest","dumbbell","strength","One_Arm_Dumbbell_Bench_Press"],
["One Arm Dumbbell Preacher Curl","biceps","dumbbell","strength","One_Arm_Dumbbell_Preacher_Curl"],
["One Arm Floor Press","triceps","barbell","strength","One_Arm_Floor_Press"],
["One Arm Lat Pulldown","lats","cable","strength","One_Arm_Lat_Pulldown"],
["One Arm Pronated Dumbbell Triceps Extension","triceps","dumbbell","strength","One_Arm_Pronated_Dumbbell_Triceps_Extension"],
["One Arm Supinated Dumbbell Triceps Extension","triceps","dumbbell","strength","One_Arm_Supinated_Dumbbell_Triceps_Extension"],
["One Half Locust","quadriceps","","stretching","One_Half_Locust"],
["One Handed Hang","lats","other","stretching","One_Handed_Hang"],
["One Knee To Chest","glutes","","stretching","One_Knee_To_Chest"],
["One Leg Barbell Squat","quadriceps","barbell","strength","One_Leg_Barbell_Squat"],
["Open Palm Kettlebell Clean","hamstrings","kettlebells","strength","Open_Palm_Kettlebell_Clean"],
["Otis-Up","abdominals","other","strength","Otis-Up"],
["Overhead Cable Curl","biceps","cable","strength","Overhead_Cable_Curl"],
["Overhead Lat","lats","other","stretching","Overhead_Lat"],
["Overhead Slam","lats","medicine ball","plyometrics","Overhead_Slam"],
["Overhead Squat","quadriceps","barbell","olympic weightlifting","Overhead_Squat"],
["Overhead Stretch","abdominals","","stretching","Overhead_Stretch"],
["Overhead Triceps","triceps","body only","stretching","Overhead_Triceps"],
["Pallof Press","abdominals","cable","strength","Pallof_Press"],
["Pallof Press With Rotation","abdominals","cable","strength","Pallof_Press_With_Rotation"],
["Palms-Down Dumbbell Wrist Curl Over A Bench","forearms","dumbbell","strength","Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench"],
["Palms-Down Wrist Curl Over A Bench","forearms","barbell","strength","Palms-Down_Wrist_Curl_Over_A_Bench"],
["Palms-Up Barbell Wrist Curl Over A Bench","forearms","barbell","strength","Palms-Up_Barbell_Wrist_Curl_Over_A_Bench"],
["Palms-Up Dumbbell Wrist Curl Over A Bench","forearms","dumbbell","strength","Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench"],
["Parallel Bar Dip","triceps","other","strength","Parallel_Bar_Dip"],
["Pelvic Tilt Into Bridge","lower back","","stretching","Pelvic_Tilt_Into_Bridge"],
["Peroneals-SMR","calves","foam roll","stretching","Peroneals-SMR"],
["Peroneals Stretch","calves","other","stretching","Peroneals_Stretch"],
["Physioball Hip Bridge","glutes","exercise ball","strength","Physioball_Hip_Bridge"],
["Pin Presses","triceps","barbell","powerlifting","Pin_Presses"],
["Piriformis-SMR","glutes","foam roll","stretching","Piriformis-SMR"],
["Plank","abdominals","body only","strength","Plank"],
["Plate Pinch","forearms","other","strength","Plate_Pinch"],
["Plate Twist","abdominals","other","strength","Plate_Twist"],
["Platform Hamstring Slides","hamstrings","other","strength","Platform_Hamstring_Slides"],
["Plie Dumbbell Squat","quadriceps","dumbbell","strength","Plie_Dumbbell_Squat"],
["Plyo Kettlebell Pushups","chest","kettlebells","strength","Plyo_Kettlebell_Pushups"],
["Plyo Push-up","chest","body only","plyometrics","Plyo_Push-up"],
["Posterior Tibialis Stretch","calves","other","stretching","Posterior_Tibialis_Stretch"],
["Power Clean","hamstrings","barbell","strength","Power_Clean"],
["Power Clean from Blocks","hamstrings","barbell","olympic weightlifting","Power_Clean_from_Blocks"],
["Power Jerk","quadriceps","barbell","olympic weightlifting","Power_Jerk"],
["Power Partials","shoulders","dumbbell","strength","Power_Partials"],
["Power Snatch","hamstrings","barbell","olympic weightlifting","Power_Snatch"],
["Power Snatch from Blocks","quadriceps","barbell","olympic weightlifting","Power_Snatch_from_Blocks"],
["Power Stairs","hamstrings","other","strongman","Power_Stairs"],
["Preacher Curl","biceps","barbell","strength","Preacher_Curl"],
["Preacher Hammer Dumbbell Curl","biceps","dumbbell","strength","Preacher_Hammer_Dumbbell_Curl"],
["Press Sit-Up","abdominals","barbell","strength","Press_Sit-Up"],
["Prone Manual Hamstring","hamstrings","","strength","Prone_Manual_Hamstring"],
["Prowler Sprint","hamstrings","other","cardio","Prowler_Sprint"],
["Pull Through","glutes","cable","strength","Pull_Through"],
["Pullups","lats","body only","strength","Pullups"],
["Push-Up Wide","chest","body only","strength","Push-Up_Wide"],
["Push-Ups - Close Triceps Position","triceps","body only","strength","Push-Ups_-_Close_Triceps_Position"],
["Push-Ups With Feet Elevated","chest","body only","strength","Push-Ups_With_Feet_Elevated"],
["Push-Ups With Feet On An Exercise Ball","chest","exercise ball","strength","Push-Ups_With_Feet_On_An_Exercise_Ball"],
["Push Press","shoulders","barbell","olympic weightlifting","Push_Press"],
["Push Press - Behind the Neck","shoulders","barbell","olympic weightlifting","Push_Press_-_Behind_the_Neck"],
["Push Up to Side Plank","chest","body only","strength","Push_Up_to_Side_Plank"],
["Pushups","chest","body only","strength","Pushups"],
["Pushups (Close and Wide Hand Positions)","chest","body only","strength","Pushups_Close_and_Wide_Hand_Positions"],
["Pyramid","lower back","exercise ball","stretching","Pyramid"],
["Quad Stretch","quadriceps","other","stretching","Quad_Stretch"],
["Quadriceps-SMR","quadriceps","foam roll","stretching","Quadriceps-SMR"],
["Quick Leap","quadriceps","other","plyometrics","Quick_Leap"],
["Rack Delivery","shoulders","barbell","olympic weightlifting","Rack_Delivery"],
["Rack Pull with Bands","lower back","barbell","powerlifting","Rack_Pull_with_Bands"],
["Rack Pulls","lower back","barbell","powerlifting","Rack_Pulls"],
["Rear Leg Raises","quadriceps","body only","stretching","Rear_Leg_Raises"],
["Recumbent Bike","quadriceps","machine","cardio","Recumbent_Bike"],
["Return Push from Stance","shoulders","medicine ball","plyometrics","Return_Push_from_Stance"],
["Reverse Band Bench Press","triceps","barbell","powerlifting","Reverse_Band_Bench_Press"],
["Reverse Band Box Squat","quadriceps","barbell","powerlifting","Reverse_Band_Box_Squat"],
["Reverse Band Deadlift","lower back","barbell","powerlifting","Reverse_Band_Deadlift"],
["Reverse Band Power Squat","quadriceps","barbell","powerlifting","Reverse_Band_Power_Squat"],
["Reverse Band Sumo Deadlift","hamstrings","barbell","powerlifting","Reverse_Band_Sumo_Deadlift"],
["Reverse Barbell Curl","biceps","barbell","strength","Reverse_Barbell_Curl"],
["Reverse Barbell Preacher Curls","biceps","e-z curl bar","strength","Reverse_Barbell_Preacher_Curls"],
["Reverse Cable Curl","biceps","cable","strength","Reverse_Cable_Curl"],
["Reverse Crunch","abdominals","body only","strength","Reverse_Crunch"],
["Reverse Flyes","shoulders","dumbbell","strength","Reverse_Flyes"],
["Reverse Flyes With External Rotation","shoulders","dumbbell","strength","Reverse_Flyes_With_External_Rotation"],
["Reverse Grip Bent-Over Rows","middle back","barbell","strength","Reverse_Grip_Bent-Over_Rows"],
["Reverse Grip Triceps Pushdown","triceps","cable","strength","Reverse_Grip_Triceps_Pushdown"],
["Reverse Hyperextension","hamstrings","machine","strength","Reverse_Hyperextension"],
["Reverse Machine Flyes","shoulders","machine","strength","Reverse_Machine_Flyes"],
["Reverse Plate Curls","biceps","other","strength","Reverse_Plate_Curls"],
["Reverse Triceps Bench Press","triceps","barbell","strength","Reverse_Triceps_Bench_Press"],
["Rhomboids-SMR","middle back","foam roll","stretching","Rhomboids-SMR"],
["Rickshaw Carry","forearms","other","strongman","Rickshaw_Carry"],
["Rickshaw Deadlift","quadriceps","other","strongman","Rickshaw_Deadlift"],
["Ring Dips","triceps","other","strength","Ring_Dips"],
["Rocket Jump","quadriceps","body only","plyometrics","Rocket_Jump"],
["Rocking Standing Calf Raise","calves","barbell","strength","Rocking_Standing_Calf_Raise"],
["Rocky Pull-Ups/Pulldowns","lats","other","strength","Rocky_Pull-Ups_Pulldowns"],
["Romanian Deadlift","hamstrings","barbell","strength","Romanian_Deadlift"],
["Romanian Deadlift from Deficit","hamstrings","barbell","olympic weightlifting","Romanian_Deadlift_from_Deficit"],
["Rope Climb","lats","other","strength","Rope_Climb"],
["Rope Crunch","abdominals","cable","strength","Rope_Crunch"],
["Rope Jumping","quadriceps","other","cardio","Rope_Jumping"],
["Rope Straight-Arm Pulldown","lats","cable","strength","Rope_Straight-Arm_Pulldown"],
["Round The World Shoulder Stretch","shoulders","other","stretching","Round_The_World_Shoulder_Stretch"],
["Rowing, Stationary","quadriceps","machine","cardio","Rowing_Stationary"],
["Runner's Stretch","hamstrings","","stretching","Runners_Stretch"],
["Running, Treadmill","quadriceps","machine","cardio","Running_Treadmill"],
["Russian Twist","abdominals","body only","strength","Russian_Twist"],
["Sandbag Load","quadriceps","other","strongman","Sandbag_Load"],
["Scapular Pull-Up","traps","","strength","Scapular_Pull-Up"],
["Scissor Kick","abdominals","body only","stretching","Scissor_Kick"],
["Scissors Jump","quadriceps","body only","plyometrics","Scissors_Jump"],
["Seated Band Hamstring Curl","hamstrings","other","strength","Seated_Band_Hamstring_Curl"],
["Seated Barbell Military Press","shoulders","barbell","strength","Seated_Barbell_Military_Press"],
["Seated Barbell Twist","abdominals","barbell","strength","Seated_Barbell_Twist"],
["Seated Bent-Over One-Arm Dumbbell Triceps Extension","triceps","dumbbell","strength","Seated_Bent-Over_One-Arm_Dumbbell_Triceps_Extension"],
["Seated Bent-Over Rear Delt Raise","shoulders","dumbbell","strength","Seated_Bent-Over_Rear_Delt_Raise"],
["Seated Bent-Over Two-Arm Dumbbell Triceps Extension","triceps","dumbbell","strength","Seated_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension"],
["Seated Biceps","biceps","body only","stretching","Seated_Biceps"],
["Seated Cable Rows","middle back","cable","strength","Seated_Cable_Rows"],
["Seated Cable Shoulder Press","shoulders","cable","strength","Seated_Cable_Shoulder_Press"],
["Seated Calf Raise","calves","machine","strength","Seated_Calf_Raise"],
["Seated Calf Stretch","calves","","stretching","Seated_Calf_Stretch"],
["Seated Close-Grip Concentration Barbell Curl","biceps","barbell","strength","Seated_Close-Grip_Concentration_Barbell_Curl"],
["Seated Dumbbell Curl","biceps","dumbbell","strength","Seated_Dumbbell_Curl"],
["Seated Dumbbell Inner Biceps Curl","biceps","dumbbell","strength","Seated_Dumbbell_Inner_Biceps_Curl"],
["Seated Dumbbell Palms-Down Wrist Curl","forearms","dumbbell","strength","Seated_Dumbbell_Palms-Down_Wrist_Curl"],
["Seated Dumbbell Palms-Up Wrist Curl","forearms","dumbbell","strength","Seated_Dumbbell_Palms-Up_Wrist_Curl"],
["Seated Dumbbell Press","shoulders","dumbbell","strength","Seated_Dumbbell_Press"],
["Seated Flat Bench Leg Pull-In","abdominals","body only","strength","Seated_Flat_Bench_Leg_Pull-In"],
["Seated Floor Hamstring Stretch","hamstrings","","stretching","Seated_Floor_Hamstring_Stretch"],
["Seated Front Deltoid","shoulders","body only","stretching","Seated_Front_Deltoid"],
["Seated Glute","glutes","body only","stretching","Seated_Glute"],
["Seated Good Mornings","lower back","barbell","powerlifting","Seated_Good_Mornings"],
["Seated Hamstring","hamstrings","","stretching","Seated_Hamstring"],
["Seated Hamstring and Calf Stretch","hamstrings","other","stretching","Seated_Hamstring_and_Calf_Stretch"],
["Seated Head Harness Neck Resistance","neck","other","strength","Seated_Head_Harness_Neck_Resistance"],
["Seated Leg Curl","hamstrings","machine","strength","Seated_Leg_Curl"],
["Seated Leg Tucks","abdominals","body only","strength","Seated_Leg_Tucks"],
["Seated One-Arm Dumbbell Palms-Down Wrist Curl","forearms","dumbbell","strength","Seated_One-Arm_Dumbbell_Palms-Down_Wrist_Curl"],
["Seated One-Arm Dumbbell Palms-Up Wrist Curl","forearms","dumbbell","strength","Seated_One-Arm_Dumbbell_Palms-Up_Wrist_Curl"],
["Seated One-arm Cable Pulley Rows","middle back","cable","strength","Seated_One-arm_Cable_Pulley_Rows"],
["Seated Overhead Stretch","abdominals","","stretching","Seated_Overhead_Stretch"],
["Seated Palm-Up Barbell Wrist Curl","forearms","barbell","strength","Seated_Palm-Up_Barbell_Wrist_Curl"],
["Seated Palms-Down Barbell Wrist Curl","forearms","barbell","strength","Seated_Palms-Down_Barbell_Wrist_Curl"],
["Seated Side Lateral Raise","shoulders","dumbbell","strength","Seated_Side_Lateral_Raise"],
["Seated Triceps Press","triceps","dumbbell","strength","Seated_Triceps_Press"],
["Seated Two-Arm Palms-Up Low-Pulley Wrist Curl","forearms","cable","strength","Seated_Two-Arm_Palms-Up_Low-Pulley_Wrist_Curl"],
["See-Saw Press (Alternating Side Press)","shoulders","dumbbell","strength","See-Saw_Press_Alternating_Side_Press"],
["Shotgun Row","lats","cable","strength","Shotgun_Row"],
["Shoulder Circles","shoulders","","stretching","Shoulder_Circles"],
["Shoulder Press - With Bands","shoulders","bands","strength","Shoulder_Press_-_With_Bands"],
["Shoulder Raise","shoulders","","stretching","Shoulder_Raise"],
["Shoulder Stretch","shoulders","","stretching","Shoulder_Stretch"],
["Side-Lying Floor Stretch","lats","","stretching","Side-Lying_Floor_Stretch"],
["Side Bridge","abdominals","body only","strength","Side_Bridge"],
["Side Hop-Sprint","quadriceps","other","plyometrics","Side_Hop-Sprint"],
["Side Jackknife","abdominals","body only","strength","Side_Jackknife"],
["Side Lateral Raise","shoulders","dumbbell","strength","Side_Lateral_Raise"],
["Side Laterals to Front Raise","shoulders","dumbbell","strength","Side_Laterals_to_Front_Raise"],
["Side Leg Raises","adductors","body only","stretching","Side_Leg_Raises"],
["Side Lying Groin Stretch","adductors","","stretching","Side_Lying_Groin_Stretch"],
["Side Neck Stretch","neck","","stretching","Side_Neck_Stretch"],
["Side Standing Long Jump","quadriceps","","plyometrics","Side_Standing_Long_Jump"],
["Side To Side Chins","lats","other","strength","Side_To_Side_Chins"],
["Side Wrist Pull","shoulders","","stretching","Side_Wrist_Pull"],
["Side to Side Box Shuffle","quadriceps","other","plyometrics","Side_to_Side_Box_Shuffle"],
["Single-Arm Cable Crossover","chest","cable","strength","Single-Arm_Cable_Crossover"],
["Single-Arm Linear Jammer","shoulders","barbell","strength","Single-Arm_Linear_Jammer"],
["Single-Arm Push-Up","chest","body only","strength","Single-Arm_Push-Up"],
["Single-Cone Sprint Drill","quadriceps","other","plyometrics","Single-Cone_Sprint_Drill"],
["Single-Leg High Box Squat","quadriceps","other","strength","Single-Leg_High_Box_Squat"],
["Single-Leg Hop Progression","quadriceps","other","plyometrics","Single-Leg_Hop_Progression"],
["Single-Leg Lateral Hop","quadriceps","other","plyometrics","Single-Leg_Lateral_Hop"],
["Single-Leg Leg Extension","quadriceps","machine","strength","Single-Leg_Leg_Extension"],
["Single-Leg Stride Jump","quadriceps","other","plyometrics","Single-Leg_Stride_Jump"],
["Single Dumbbell Raise","shoulders","dumbbell","strength","Single_Dumbbell_Raise"],
["Single Leg Butt Kick","quadriceps","body only","plyometrics","Single_Leg_Butt_Kick"],
["Single Leg Glute Bridge","glutes","body only","strength","Single_Leg_Glute_Bridge"],
["Single Leg Push-off","quadriceps","other","plyometrics","Single_Leg_Push-off"],
["Sit-Up","abdominals","body only","strength","Sit-Up"],
["Sit Squats","quadriceps","","stretching","Sit_Squats"],
["Skating","quadriceps","other","cardio","Skating"],
["Sled Drag - Harness","quadriceps","other","strongman","Sled_Drag_-_Harness"],
["Sled Overhead Backward Walk","shoulders","other","strength","Sled_Overhead_Backward_Walk"],
["Sled Overhead Triceps Extension","triceps","other","strength","Sled_Overhead_Triceps_Extension"],
["Sled Push","quadriceps","other","strongman","Sled_Push"],
["Sled Reverse Flye","shoulders","other","strength","Sled_Reverse_Flye"],
["Sled Row","middle back","other","strength","Sled_Row"],
["Sledgehammer Swings","abdominals","other","plyometrics","Sledgehammer_Swings"],
["Smith Incline Shoulder Raise","shoulders","barbell","strength","Smith_Incline_Shoulder_Raise"],
["Smith Machine Behind the Back Shrug","traps","machine","strength","Smith_Machine_Behind_the_Back_Shrug"],
["Smith Machine Bench Press","chest","machine","strength","Smith_Machine_Bench_Press"],
["Smith Machine Bent Over Row","middle back","machine","strength","Smith_Machine_Bent_Over_Row"],
["Smith Machine Calf Raise","calves","machine","strength","Smith_Machine_Calf_Raise"],
["Smith Machine Close-Grip Bench Press","triceps","machine","strength","Smith_Machine_Close-Grip_Bench_Press"],
["Smith Machine Decline Press","chest","machine","strength","Smith_Machine_Decline_Press"],
["Smith Machine Hang Power Clean","hamstrings","machine","strength","Smith_Machine_Hang_Power_Clean"],
["Smith Machine Hip Raise","abdominals","machine","strength","Smith_Machine_Hip_Raise"],
["Smith Machine Incline Bench Press","chest","machine","strength","Smith_Machine_Incline_Bench_Press"],
["Smith Machine Leg Press","quadriceps","machine","strength","Smith_Machine_Leg_Press"],
["Smith Machine One-Arm Upright Row","shoulders","machine","strength","Smith_Machine_One-Arm_Upright_Row"],
["Smith Machine Overhead Shoulder Press","shoulders","machine","strength","Smith_Machine_Overhead_Shoulder_Press"],
["Smith Machine Pistol Squat","quadriceps","machine","strength","Smith_Machine_Pistol_Squat"],
["Smith Machine Reverse Calf Raises","calves","machine","strength","Smith_Machine_Reverse_Calf_Raises"],
["Smith Machine Squat","quadriceps","machine","strength","Smith_Machine_Squat"],
["Smith Machine Stiff-Legged Deadlift","hamstrings","machine","strength","Smith_Machine_Stiff-Legged_Deadlift"],
["Smith Machine Upright Row","traps","machine","strength","Smith_Machine_Upright_Row"],
["Smith Single-Leg Split Squat","quadriceps","machine","strength","Smith_Single-Leg_Split_Squat"],
["Snatch","quadriceps","barbell","olympic weightlifting","Snatch"],
["Snatch Balance","quadriceps","barbell","olympic weightlifting","Snatch_Balance"],
["Snatch Deadlift","hamstrings","barbell","olympic weightlifting","Snatch_Deadlift"],
["Snatch Pull","hamstrings","barbell","strength","Snatch_Pull"],
["Snatch Shrug","traps","barbell","olympic weightlifting","Snatch_Shrug"],
["Snatch from Blocks","quadriceps","barbell","olympic weightlifting","Snatch_from_Blocks"],
["Speed Band Overhead Triceps","triceps","bands","strength","Speed_Band_Overhead_Triceps"],
["Speed Box Squat","quadriceps","barbell","powerlifting","Speed_Box_Squat"],
["Speed Squats","quadriceps","barbell","strength","Speed_Squats"],
["Spell Caster","abdominals","dumbbell","strength","Spell_Caster"],
["Spider Crawl","abdominals","body only","strength","Spider_Crawl"],
["Spider Curl","biceps","e-z curl bar","strength","Spider_Curl"],
["Spinal Stretch","middle back","","stretching","Spinal_Stretch"],
["Split Clean","quadriceps","barbell","olympic weightlifting","Split_Clean"],
["Split Jerk","quadriceps","barbell","olympic weightlifting","Split_Jerk"],
["Split Jump","quadriceps","body only","plyometrics","Split_Jump"],
["Split Snatch","hamstrings","barbell","olympic weightlifting","Split_Snatch"],
["Split Squat with Dumbbells","quadriceps","dumbbell","strength","Split_Squat_with_Dumbbells"],
["Split Squats","hamstrings","","stretching","Split_Squats"],
["Squat Jerk","quadriceps","barbell","strength","Squat_Jerk"],
["Squat with Bands","quadriceps","barbell","powerlifting","Squat_with_Bands"],
["Squat with Chains","quadriceps","barbell","powerlifting","Squat_with_Chains"],
["Squat with Plate Movers","quadriceps","barbell","strength","Squat_with_Plate_Movers"],
["Squats - With Bands","quadriceps","bands","strength","Squats_-_With_Bands"],
["Stairmaster","quadriceps","machine","cardio","Stairmaster"],
["Standing Alternating Dumbbell Press","shoulders","dumbbell","strength","Standing_Alternating_Dumbbell_Press"],
["Standing Barbell Calf Raise","calves","barbell","strength","Standing_Barbell_Calf_Raise"],
["Standing Barbell Press Behind Neck","shoulders","barbell","strength","Standing_Barbell_Press_Behind_Neck"],
["Standing Bent-Over One-Arm Dumbbell Triceps Extension","triceps","dumbbell","strength","Standing_Bent-Over_One-Arm_Dumbbell_Triceps_Extension"],
["Standing Bent-Over Two-Arm Dumbbell Triceps Extension","triceps","dumbbell","strength","Standing_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension"],
["Standing Biceps Cable Curl","biceps","cable","strength","Standing_Biceps_Cable_Curl"],
["Standing Biceps Stretch","biceps","other","stretching","Standing_Biceps_Stretch"],
["Standing Bradford Press","shoulders","barbell","strength","Standing_Bradford_Press"],
["Standing Cable Chest Press","chest","cable","strength","Standing_Cable_Chest_Press"],
["Standing Cable Lift","abdominals","cable","strength","Standing_Cable_Lift"],
["Standing Cable Wood Chop","abdominals","cable","strength","Standing_Cable_Wood_Chop"],
["Standing Calf Raises","calves","machine","strength","Standing_Calf_Raises"],
["Standing Concentration Curl","biceps","dumbbell","strength","Standing_Concentration_Curl"],
["Standing Dumbbell Calf Raise","calves","dumbbell","strength","Standing_Dumbbell_Calf_Raise"],
["Standing Dumbbell Press","shoulders","dumbbell","strength","Standing_Dumbbell_Press"],
["Standing Dumbbell Reverse Curl","biceps","dumbbell","strength","Standing_Dumbbell_Reverse_Curl"],
["Standing Dumbbell Straight-Arm Front Delt Raise Above Head","shoulders","dumbbell","strength","Standing_Dumbbell_Straight-Arm_Front_Delt_Raise_Above_Head"],
["Standing Dumbbell Triceps Extension","triceps","dumbbell","strength","Standing_Dumbbell_Triceps_Extension"],
["Standing Dumbbell Upright Row","traps","dumbbell","strength","Standing_Dumbbell_Upright_Row"],
["Standing Elevated Quad Stretch","quadriceps","other","stretching","Standing_Elevated_Quad_Stretch"],
["Standing Front Barbell Raise Over Head","shoulders","barbell","strength","Standing_Front_Barbell_Raise_Over_Head"],
["Standing Gastrocnemius Calf Stretch","calves","","stretching","Standing_Gastrocnemius_Calf_Stretch"],
["Standing Hamstring and Calf Stretch","hamstrings","other","stretching","Standing_Hamstring_and_Calf_Stretch"],
["Standing Hip Circles","abductors","body only","stretching","Standing_Hip_Circles"],
["Standing Hip Flexors","quadriceps","","stretching","Standing_Hip_Flexors"],
["Standing Inner-Biceps Curl","biceps","dumbbell","strength","Standing_Inner-Biceps_Curl"],
["Standing Lateral Stretch","abdominals","","stretching","Standing_Lateral_Stretch"],
["Standing Leg Curl","hamstrings","machine","strength","Standing_Leg_Curl"],
["Standing Long Jump","quadriceps","body only","plyometrics","Standing_Long_Jump"],
["Standing Low-Pulley Deltoid Raise","shoulders","cable","strength","Standing_Low-Pulley_Deltoid_Raise"],
["Standing Low-Pulley One-Arm Triceps Extension","triceps","cable","strength","Standing_Low-Pulley_One-Arm_Triceps_Extension"],
["Standing Military Press","shoulders","barbell","strength","Standing_Military_Press"],
["Standing Olympic Plate Hand Squeeze","forearms","other","strength","Standing_Olympic_Plate_Hand_Squeeze"],
["Standing One-Arm Cable Curl","biceps","cable","strength","Standing_One-Arm_Cable_Curl"],
["Standing One-Arm Dumbbell Curl Over Incline Bench","biceps","dumbbell","strength","Standing_One-Arm_Dumbbell_Curl_Over_Incline_Bench"],
["Standing One-Arm Dumbbell Triceps Extension","triceps","dumbbell","strength","Standing_One-Arm_Dumbbell_Triceps_Extension"],
["Standing Overhead Barbell Triceps Extension","triceps","barbell","strength","Standing_Overhead_Barbell_Triceps_Extension"],
["Standing Palm-In One-Arm Dumbbell Press","shoulders","dumbbell","strength","Standing_Palm-In_One-Arm_Dumbbell_Press"],
["Standing Palms-In Dumbbell Press","shoulders","dumbbell","strength","Standing_Palms-In_Dumbbell_Press"],
["Standing Palms-Up Barbell Behind The Back Wrist Curl","forearms","barbell","strength","Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl"],
["Standing Pelvic Tilt","lower back","","stretching","Standing_Pelvic_Tilt"],
["Standing Rope Crunch","abdominals","cable","strength","Standing_Rope_Crunch"],
["Standing Soleus And Achilles Stretch","calves","","stretching","Standing_Soleus_And_Achilles_Stretch"],
["Standing Toe Touches","hamstrings","","stretching","Standing_Toe_Touches"],
["Standing Towel Triceps Extension","triceps","body only","strength","Standing_Towel_Triceps_Extension"],
["Standing Two-Arm Overhead Throw","shoulders","medicine ball","plyometrics","Standing_Two-Arm_Overhead_Throw"],
["Star Jump","quadriceps","body only","plyometrics","Star_Jump"],
["Step-up with Knee Raise","glutes","body only","strength","Step-up_with_Knee_Raise"],
["Step Mill","quadriceps","machine","cardio","Step_Mill"],
["Stiff-Legged Barbell Deadlift","hamstrings","barbell","strength","Stiff-Legged_Barbell_Deadlift"],
["Stiff-Legged Dumbbell Deadlift","hamstrings","dumbbell","strength","Stiff-Legged_Dumbbell_Deadlift"],
["Stiff Leg Barbell Good Morning","lower back","barbell","strength","Stiff_Leg_Barbell_Good_Morning"],
["Stomach Vacuum","abdominals","body only","stretching","Stomach_Vacuum"],
["Straight-Arm Dumbbell Pullover","chest","dumbbell","strength","Straight-Arm_Dumbbell_Pullover"],
["Straight-Arm Pulldown","lats","cable","strength","Straight-Arm_Pulldown"],
["Straight Bar Bench Mid Rows","middle back","barbell","strength","Straight_Bar_Bench_Mid_Rows"],
["Straight Raises on Incline Bench","shoulders","barbell","strength","Straight_Raises_on_Incline_Bench"],
["Stride Jump Crossover","quadriceps","other","plyometrics","Stride_Jump_Crossover"],
["Sumo Deadlift","hamstrings","barbell","powerlifting","Sumo_Deadlift"],
["Sumo Deadlift with Bands","hamstrings","barbell","powerlifting","Sumo_Deadlift_with_Bands"],
["Sumo Deadlift with Chains","hamstrings","barbell","powerlifting","Sumo_Deadlift_with_Chains"],
["Superman","lower back","body only","stretching","Superman"],
["Supine Chest Throw","triceps","medicine ball","plyometrics","Supine_Chest_Throw"],
["Supine One-Arm Overhead Throw","abdominals","medicine ball","plyometrics","Supine_One-Arm_Overhead_Throw"],
["Supine Two-Arm Overhead Throw","abdominals","medicine ball","plyometrics","Supine_Two-Arm_Overhead_Throw"],
["Suspended Fallout","abdominals","other","strength","Suspended_Fallout"],
["Suspended Push-Up","chest","other","strength","Suspended_Push-Up"],
["Suspended Reverse Crunch","abdominals","other","strength","Suspended_Reverse_Crunch"],
["Suspended Row","middle back","other","strength","Suspended_Row"],
["Suspended Split Squat","quadriceps","other","strength","Suspended_Split_Squat"],
["Svend Press","chest","other","strength","Svend_Press"],
["T-Bar Row with Handle","middle back","barbell","strength","T-Bar_Row_with_Handle"],
["Tate Press","triceps","dumbbell","strength","Tate_Press"],
["The Straddle","hamstrings","","stretching","The_Straddle"],
["Thigh Abductor","abductors","machine","strength","Thigh_Abductor"],
["Thigh Adductor","adductors","machine","strength","Thigh_Adductor"],
["Tire Flip","quadriceps","other","strongman","Tire_Flip"],
["Toe Touchers","abdominals","body only","stretching","Toe_Touchers"],
["Torso Rotation","abdominals","exercise ball","stretching","Torso_Rotation"],
["Trail Running/Walking","quadriceps","","cardio","Trail_Running_Walking"],
["Trap Bar Deadlift","quadriceps","other","strength","Trap_Bar_Deadlift"],
["Tricep Dumbbell Kickback","triceps","dumbbell","strength","Tricep_Dumbbell_Kickback"],
["Tricep Side Stretch","triceps","","stretching","Tricep_Side_Stretch"],
["Triceps Overhead Extension with Rope","triceps","cable","strength","Triceps_Overhead_Extension_with_Rope"],
["Triceps Pushdown","triceps","cable","strength","Triceps_Pushdown"],
["Triceps Pushdown - Rope Attachment","triceps","cable","strength","Triceps_Pushdown_-_Rope_Attachment"],
["Triceps Pushdown - V-Bar Attachment","triceps","cable","strength","Triceps_Pushdown_-_V-Bar_Attachment"],
["Triceps Stretch","triceps","","stretching","Triceps_Stretch"],
["Tuck Crunch","abdominals","body only","strength","Tuck_Crunch"],
["Two-Arm Dumbbell Preacher Curl","biceps","dumbbell","strength","Two-Arm_Dumbbell_Preacher_Curl"],
["Two-Arm Kettlebell Clean","shoulders","kettlebells","strength","Two-Arm_Kettlebell_Clean"],
["Two-Arm Kettlebell Jerk","shoulders","kettlebells","strength","Two-Arm_Kettlebell_Jerk"],
["Two-Arm Kettlebell Military Press","shoulders","kettlebells","strength","Two-Arm_Kettlebell_Military_Press"],
["Two-Arm Kettlebell Row","middle back","kettlebells","strength","Two-Arm_Kettlebell_Row"],
["Underhand Cable Pulldowns","lats","cable","strength","Underhand_Cable_Pulldowns"],
["Upper Back-Leg Grab","hamstrings","","stretching","Upper_Back-Leg_Grab"],
["Upper Back Stretch","middle back","","stretching","Upper_Back_Stretch"],
["Upright Barbell Row","shoulders","barbell","strength","Upright_Barbell_Row"],
["Upright Cable Row","traps","cable","strength","Upright_Cable_Row"],
["Upright Row - With Bands","traps","bands","strength","Upright_Row_-_With_Bands"],
["Upward Stretch","shoulders","","stretching","Upward_Stretch"],
["V-Bar Pulldown","lats","cable","strength","V-Bar_Pulldown"],
["V-Bar Pullup","lats","body only","strength","V-Bar_Pullup"],
["Vertical Swing","hamstrings","dumbbell","plyometrics","Vertical_Swing"],
["Walking, Treadmill","quadriceps","machine","cardio","Walking_Treadmill"],
["Weighted Ball Hyperextension","lower back","exercise ball","strength","Weighted_Ball_Hyperextension"],
["Weighted Ball Side Bend","abdominals","exercise ball","strength","Weighted_Ball_Side_Bend"],
["Weighted Bench Dip","triceps","other","strength","Weighted_Bench_Dip"],
["Weighted Crunches","abdominals","medicine ball","strength","Weighted_Crunches"],
["Weighted Jump Squat","quadriceps","barbell","strength","Weighted_Jump_Squat"],
["Weighted Pull Ups","lats","other","strength","Weighted_Pull_Ups"],
["Weighted Sissy Squat","quadriceps","barbell","strength","Weighted_Sissy_Squat"],
["Weighted Sit-Ups - With Bands","abdominals","other","strength","Weighted_Sit-Ups_-_With_Bands"],
["Weighted Squat","quadriceps","other","strength","Weighted_Squat"],
["Wide-Grip Barbell Bench Press","chest","barbell","strength","Wide-Grip_Barbell_Bench_Press"],
["Wide-Grip Decline Barbell Bench Press","chest","barbell","strength","Wide-Grip_Decline_Barbell_Bench_Press"],
["Wide-Grip Decline Barbell Pullover","chest","barbell","strength","Wide-Grip_Decline_Barbell_Pullover"],
["Wide-Grip Lat Pulldown","lats","cable","strength","Wide-Grip_Lat_Pulldown"],
["Wide-Grip Pulldown Behind The Neck","lats","cable","strength","Wide-Grip_Pulldown_Behind_The_Neck"],
["Wide-Grip Rear Pull-Up","lats","body only","strength","Wide-Grip_Rear_Pull-Up"],
["Wide-Grip Standing Barbell Curl","biceps","barbell","strength","Wide-Grip_Standing_Barbell_Curl"],
["Wide Stance Barbell Squat","quadriceps","barbell","strength","Wide_Stance_Barbell_Squat"],
["Wide Stance Stiff Legs","hamstrings","barbell","olympic weightlifting","Wide_Stance_Stiff_Legs"],
["Wind Sprints","abdominals","body only","strength","Wind_Sprints"],
["Windmills","abductors","","stretching","Windmills"],
["World's Greatest Stretch","hamstrings","","stretching","Worlds_Greatest_Stretch"],
["Wrist Circles","forearms","body only","stretching","Wrist_Circles"],
["Wrist Roller","forearms","other","strength","Wrist_Roller"],
["Wrist Rotations with Straight Bar","forearms","barbell","strength","Wrist_Rotations_with_Straight_Bar"],
["Yoke Walk","quadriceps","other","strongman","Yoke_Walk"],
["Zercher Squats","quadriceps","barbell","strength","Zercher_Squats"],
["Zottman Curl","biceps","dumbbell","strength","Zottman_Curl"],
["Zottman Preacher Curl","biceps","dumbbell","strength","Zottman_Preacher_Curl"]
];
if (typeof module !== 'undefined' && module.exports) module.exports = EXERCISES; else g.EXERCISES = EXERCISES;
})(typeof window !== 'undefined' ? window : this);
